baseURL: https://steven-emelianenko.netlify.app/
languageCode: en-us
title: Mr. Emelianenko & his life
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get to know me
    subtitle: |-
      Some insight into my professional and personal life
    title: Hi, my name is not Forty (more of Steven or Stepan, tbh)
  blog: {Stepan Emelianenko}
  contact:
    address:
      - city: Cannes, 06400
        country: France
        street: 1 Boulevard de la Croisette
        title: Address (not mine, but you should go there)
    buttonClear: Oh my God, what happened, how to erase?
    buttonSend: Git push
    email:
      - email: semelianenko.mfa2022@london.edu
        title: LBS Email
    enable: yes
    phone:
      - phone: +7 (800) 700 5050
        title: National Antidrug Unit Phone (it could help somebody)
  custom_css: []
  custom_js: []
  description: I don't know where it appears :)
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School
    enable: yes
    quicklinks:
      - alt: LBS
        text: 'LBS website: '
        url: https://www.london.edu
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com
#      - icon: fa-facebook
#        label: Facebook
#        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/stevem_17
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/Stevemel17
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/stepan-emelianenko/
  image: ''
  name: Stepan Emelianenko
  navigation:
    button1:
      - name: Get Started
        url: blogs
#    button2:
#      - name: Log In
#        url: '#'
    links:
      - name: Starting page
        url: '#'
      - name: My CV
        url: blogs/cv
      - name: My group
        url: blogs/group
#      - name: Elements
#        url: elements.html
    menu: Menu
    subtitle: site
    title: Web
  tiles:
    enable: yes
    showcase:
      - image: office.jpg
        subtitle: Take a look at my CV
        title: CV
        url: blogs/cv
      - image: pic02.jpg
        subtitle: Learn more about me!
        title: My interests
        url: blogs/interests
      - image: p1.png
        subtitle: Learn more about Group A06
        title: My group
        url: blogs/group
      - image: pr_name.png
        subtitle: Data analytics on accommodation prices in Amsterdam
        title: Our AirBnB analytics
        url: blogs/project
#      - image: pic05.jpg
#        subtitle: Ipsum Dolor Sit Amet
#        title: Consequat
#        url: blogs/ipsum
#      - image: pic06.jpg
#        subtitle: Feugiat Amet Tempus
#        title: Etiam
#        url: blogs/ipsum
  two:
    buttonText: Go straight to the content
    enable: yes
    subtitle: "All in all, I liked the material of the course and Kostis in particular.
    His approach is engaging and unique which makes you want to study.
    However, I doubt the timing of the course and its relevance for MFA right now.
    I have spent all the classes staring into my screen and doing my applications instead
    studying. I have learnt far less than I could have learnt, unfortunately, as I
    had to prepare for interviews (which I have not gotten yet, but I still hope for
    something). Thnaks God and admin staff that we can replay the course and restudy it on
    Christmas holidays. Anyway, please find some things I learnt on this website. I
    can only thank you for hard work and 24/7 support and continue my tries to find a job :)"
    title: My thoughts on the course
    url: blogs
